spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/Demo2
    username: root
    password: 123456789
  jpa:
    database: mysql
    show_sql: true
    hibernate:
      ddl-auto: create - drop

